spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/employee
    password: adeniran1995@mysql
    username: root
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL#Dialect
        format_sql: true
  